import { Alert } from "react-bootstrap";

const showExampleText = () => {
    return (
        // <Alert
        //     style={{
        //         width: "80%",
        //         marginTop: "20px",
        //         textAlign: "left",
        //     }}>
        <div>
            <div>
                <h4>
                    {" "}
                    Example: <i>Amy buys fruits</i>
                </h4>
            </div>
            <p>
                <ul>
                    <li>
                        {" "}
                        Context:{" "}
                        <i>
                            Amy went to the supermarket and bought 3 apples and
                            2 pears. She then looked for some bread and cheese.
                            She could not find bread but found herself some
                            cheese. Just before getting to the checkout line,
                            she bought a watermelon.
                        </i>{" "}
                    </li>
                    <li>Question: How many fruits did Amy buy?</li>
                    <li>
                        Generated correct answer: 6<br></br>
                    </li>
                    <li>
                        Rationale for generated answer (Format: Annotated
                        Report): <br></br>
                    </li>
                    <ul>
                        <li>
                            <b>1. Quote from context:</b> “bought 3 apples and 2
                            pears” <br></br>
                            <b>Annotation:</b> Amy bought 5 fruits at first.
                        </li>
                        <li>
                            <b>2. Quote from context:</b> “looked for some bread
                            and cheese.” <br></br>
                            <b>Annotation:</b> Amy bought 2 more fruits.
                        </li>
                    </ul>
                </ul>
            </p>{" "}
        </div>
        // </Alert>
    );
};
const ContextQuestion = (props) => {
    return (
        <div>
            <Alert
                style={{
                    width: "80%",
                    marginTop: "20px",
                    textAlign: "left",
                }}>
                <p>
                    <h4> Instructions </h4> <br></br>
                    In this task, you will be looking at a context (text
                    snippet), a question based on the context, and{" "}
                    <b>
                        correct answers to the question generated by an AI
                        model.
                    </b>{" "}
                    You will be asked to label how well you understand and trust
                    the model’s reasoning. <br></br>{" "}
                </p>
                <p>
                    <b>All answers are generated based on a rationale</b>, which
                    essentially outlines the process of how the model found the
                    answer. You will be presented with{" "}
                    <b>multiple rationale formats</b> along with their
                    corresponding generated answers. Based on the generated
                    correct answer, we will ask you to evaluate{" "}
                    <b>each rationale format</b>. Specifically, you will be
                    presented with the following input:{" "}
                </p>
                <p>
                    <ul>
                        <li>
                            a snippet of text as the <b>context</b>
                        </li>
                        <li>
                            a <b>question</b> based on this context
                        </li>
                        <li>
                            <div
                                style={{
                                    display: "flex",
                                    flexDirection: "row",
                                }}>
                                <div>
                                    <b>
                                        {" "}
                                        generated correct answers (corresponding
                                        to each rationale){" "}
                                    </b>{" "}
                                    generated by the AI model
                                </div>
                            </div>
                        </li>
                        <li>
                            <b>rationales</b> based on the context generated by
                            the AI model to attempt at answering the question
                        </li>
                    </ul>
                </p>
                <p>
                    A good rationale should be sufficient to answer the question
                    on its own without the context and faithful to the
                    information in the context. You will need to judge how{" "}
                    <b>interpretable</b> the rationale is in improving your
                    understanding of the AI model’s reasoning and how{" "}
                    <b>trustworthy</b> you find the answer given the rationale.
                </p>
                <br></br>
                <p style={{ color: "green" }}>
                    **
                    <b>
                        Here is an example of what you might see--make sure you
                        read this carefully before starting the task:**
                    </b>
                </p>
                <p></p>
                {showExampleText()}
            </Alert>
        </div>
    );
};

export default ContextQuestion;
