import { Alert } from "react-bootstrap";

const showExampleText = () => {
    return (
        // <Alert
        //     style={{
        //         width: "80%",
        //         marginTop: "20px",
        //         textAlign: "left",
        //     }}>
        <div>
            <div>
                <h4>
                    {" "}
                    Example: <i>Amy buys fruits</i>
                </h4>
            </div>
            <p>
                <ul>
                    <li>
                        {" "}
                        Context:{" "}
                        <i>
                            Amy went to the supermarket and bought 3 apples and
                            2 pears. She then looked for some bread and cheese.
                            She could not find bread but found herself some
                            cheese. Just before getting to the checkout line,
                            she bought a watermelon.
                        </i>{" "}
                    </li>
                    <li>Question: How many fruits did Amy buy?</li>
                    <li>
                        Reference correct answer: 6<br></br>
                    </li>
                    <li>
                        Generated incorrect answer: 7<br></br>
                    </li>{" "}
                    <li>
                        Rationale for generated answer (Format: Annotated
                        Report): <br></br>
                    </li>
                    <ul>
                        <li>
                            <b>1. Quote from context:</b> “bought 3 apples and 2
                            pears” <br></br>
                            <b>Annotation:</b> Amy bought 5 fruits at first.
                        </li>
                        <li>
                            <b>2. Quote from context:</b> “looked for some bread
                            and cheese.” <br></br>
                            <b>Annotation:</b> Amy bought 2 more fruits.
                        </li>
                    </ul>
                </ul>
            </p>{" "}
            <p>
                As mentioned, your task is to label whether the rationale is
                sufficient on its own to answer the question, as well as whether
                it is faithful to the information in the context. In the above
                example, the rationale is <b>sufficient</b> because it{" "}
                <b>does</b> contain enough information to determine an answer
                (although an incorrect one), using the rationale alone. On the
                other hand, the rationale is completely <b>unfaithful</b> to the
                context as the information in the rationale inaccurately
                represents information in the context.
            </p>
        </div>
        // </Alert>
    );
};
const ContextQuestion = (props) => {
    return (
        <div>
            <Alert
                style={{
                    width: "80%",
                    marginTop: "20px",
                    textAlign: "left",
                }}>
                <p>
                    <h4> Instructions </h4> <br></br>
                    In this task, you will be looking at a context (text
                    snippet), a question based on the context, a reference
                    correct answer to the question, and{" "}
                    <b>incorrect answers generated by an AI model</b> to the
                    question. You will be asked to analyze what went wrong, as
                    well as give feedback to the AI model to fix it. <br></br>{" "}
                </p>
                <p>
                    <b>
                        All incorrect answers are generated based on a rationale
                    </b>
                    , which essentially outlines the process of how the model
                    found the answer. You will be presented with{" "}
                    <b>multiple rationale formats</b> along with their
                    corresponding generated answers. Based on the reference
                    correct answer, we will ask you to evaluate{" "}
                    <b>each rationale format</b>. Specifically, you will be
                    presented with the following input:{" "}
                </p>
                <p>
                    <ul>
                        <li>
                            a snippet of text as the <b>context</b>
                        </li>
                        <li>
                            a <b>question</b> based on this context
                        </li>
                        <li>
                            <div
                                style={{
                                    display: "flex",
                                    flexDirection: "row",
                                }}>
                                <div>
                                    the <b> reference correct answer</b>{" "}
                                </div>
                                <div
                                    style={{
                                        color: "#333333",
                                        marginLeft: "3px",
                                        fontSize: "17px",
                                    }}>
                                    {" "}
                                    *{" "}
                                </div>
                            </div>
                        </li>
                        <li>
                            <b>
                                predicted incorrect answers (corresponding to
                                each rationale){" "}
                            </b>{" "}
                            generated by the AI model
                        </li>
                        <li>
                            <b>rationales</b> based on the context generated by
                            the AI model to attempt at answering the question
                        </li>
                    </ul>
                </p>
                <p style={{ color: "#333333" }}>
                    <i>
                        * Very rarely, the reference answer might be inaccurate.
                        If so, continue the study with what you think is the
                        correct answer
                    </i>
                </p>
                <p>
                    You will first need to evaluate whether a rationale is 1){" "}
                    <b>
                        {" "}
                        sufficient to answer the question (not necessarily
                        correctly) on its own <i> without </i> the context,
                    </b>{" "}
                    <b> 2) faithful to the information in the context. </b>{" "}
                    Finally, you will need to provide{" "}
                    <b> textual feedback for the rationale. </b>
                </p>
                <br></br>
                <p style={{ color: "green" }}>
                    **
                    <b>
                        Here is an example of what you might see--make sure you
                        read this carefully before starting the task:**
                    </b>
                </p>
                <p></p>
                {showExampleText()}
            </Alert>
        </div>
    );
};

export default ContextQuestion;
