import React from "react";
import { Alert, Card } from "react-bootstrap";
import Slider from "./Slider";

const FeedbackSliders = (props) => {
    return (
        <div id="rationale-answer-section">
            {" "}
            <Alert
                style={{
                    width: "80%",
                    marginTop: "20px",
                    textAlign: "left",
                }}>
                <h4> Rationale Assessment </h4>
                Now that you have seen all rationale formats, we are interested
                in your assessment of the characteristics that you value in
                rationales generated by an AI model. Please rate the following
                characteristics of rationales based on how much you value them,
                on a <b>scale of 1-5 (default is set to 3).</b> <br></br>
                <br></br>
                <p>
                    <b>
                        To make it easier, we provided as reference all five
                        rationale formats and their examples. Please look below
                        and review them as you are assessing the qualities*
                    </b>
                </p>
            </Alert>
            <Card
                style={{ width: "80%", marginTop: "20px", textAlign: "left" }}>
                <Card.Body>
                    <Card.Title>
                        <div style={{ display: "flex", flexDirection: "row" }}>
                            Qualities
                            <div
                                style={{
                                    color: "red",
                                    marginLeft: "3px",
                                    fontSize: "17px",
                                }}>
                                {" "}
                                *{" "}
                            </div>
                        </div>
                    </Card.Title>
                    <br></br>
                    <Card.Text>
                        <Slider
                            title="Quotes from Context:"
                            content="How important is it for you that the rationales include direct quotes from the context?"
                            feedbackValues={props.feedbackValues}
                            setFeedbackValues={props.setFeedbackValues}
                            index={0}
                        />
                        <br></br>
                        <Slider
                            title="Depth of reasoning exposed:"
                            content="How important is it for you that the rationale provides detailed insight into the reasoning process?"
                            feedbackValues={props.feedbackValues}
                            setFeedbackValues={props.setFeedbackValues}
                            index={1}
                        />
                        <br></br>
                        <Slider
                            title="Reasoning presented in a sequential manner:"
                            content="How important is it for you that the rationale is organized in a step-by-step or sequential manner?"
                            feedbackValues={props.feedbackValues}
                            setFeedbackValues={props.setFeedbackValues}
                            index={2}
                        />
                        <br></br>
                        <Slider
                            title="Structure of the rationale:"
                            content="How important is it for you that the rationale follows a strict format with well-defined operations in each step?"
                            feedbackValues={props.feedbackValues}
                            setFeedbackValues={props.setFeedbackValues}
                            index={3}
                        />
                        <br></br>
                        <Slider
                            title="Conciseness:"
                            content="How important is it for you that the rationale is brief and to the point?"
                            feedbackValues={props.feedbackValues}
                            setFeedbackValues={props.setFeedbackValues}
                            index={4}
                        />
                    </Card.Text>
                </Card.Body>
            </Card>
            <Alert
                style={{
                    width: "80%",
                    marginTop: "20px",
                    textAlign: "left",
                }}>
                <p>
                    {" "}
                    <h4> *Reference: Rational Formats and Examples </h4>
                    <br></br>
                </p>
                <p>
                    <b>Markup and Mask:</b> A set of extracted sentences from
                    the context which are additionally marked up with what
                    pronouns and ambiguous phrases refer to, in square brackets.{" "}
                    <br></br> <br></br>
                    <b>1. Quote from context: </b>Amy went to the supermarket
                    and bought 3 apples and 2 pears.” <br></br>{" "}
                    <b>2. Quote from context: </b>“Just before getting to the
                    checkout line, she <b>[Amy]</b> picked up a watermelon.”
                    <br></br>
                    -----------------------------------------------------------------------------------------------------------------------
                </p>
                <p>
                    <b>Annotated Report:</b> A list of extracted phrases from
                    the context and what each phrase indicates. <br></br>{" "}
                    <br></br>
                    <b>1. Quote from context:</b> “bought 3 apples and 2 pears”{" "}
                    <br></br>
                    <b>Annotation:</b> Amy bought 5 fruits at first. <br></br>{" "}
                    <br></br>
                    <b>2. Quote from context:</b> “she picked up a watermelon”{" "}
                    <br></br>
                    <b>Annotation:</b> Amy bought 1 other fruit.
                    <br></br>
                    -----------------------------------------------------------------------------------------------------------------------
                </p>
                <p>
                    <b>Procedural:</b> A step-by-step plan of solving the
                    question where each step can be one of the following
                    operations:
                    <ul>
                        <li>
                            Extract-relevant-sentences → extracts sentences from
                            the context relevant to answering the question)
                        </li>
                        <li>
                            Disambiguate-question-entity (s) → determines the
                            specific entity or phrase that the phrase s in the
                            question refers to
                        </li>
                        <li>
                            Disambiguate-plan-entity (s) → determines the
                            specific entity or phrase that the phrase s in the
                            plan so far refers to
                        </li>
                        <li>
                            Locate-entity (s) → Answers a subquestion s that is
                            important to answer the original question
                        </li>
                    </ul>{" "}
                    1) <b>Extract-relevant-sentences:</b> “Amy went to the
                    supermarket and bought 3 apples and 2 pears.”, “Just before
                    getting to the checkout line, she picked up a watermelon.”{" "}
                    <br></br>
                    2)<b> Disambiguate-plan-entity</b> (“she”): “Amy”. <br></br>{" "}
                    3) <b>Locate-entity</b> (“how many fruits did she buy at
                    first?”): “5” <br></br>4) <b>Locate-entity</b> (“how many
                    fruits did she buy before getting to the checkout line?”):
                    1.
                    <br></br>
                    -----------------------------------------------------------------------------------------------------------------------
                </p>
                <p>
                    <b>Subquestions</b> A breakdown of the original question
                    into subquestions that are helpful for answering the
                    original question. <br></br> <br></br>
                    <b>Q1: How many apples did Amy buy?</b>
                    <br></br>A: 3.<br></br>
                    <br></br> <b>Q2: How many pears did Amy buy?</b>
                    <br></br>A: 2. <br></br>
                    <br></br>
                    <b>Q3: Did Amy buy any other fruits?</b>
                    <br></br>A: No.
                    <br></br>
                    -----------------------------------------------------------------------------------------------------------------------
                </p>
                <p>
                    <b>Decision Tree:</b> A breakdown of the original question
                    into subquestions presented in a tree structure, with Yes /
                    No outcomes for each subquestion. <br></br> <br></br>
                    <ul>
                        <li>
                            <b>Start</b>
                        </li>
                        <li>
                            <b>Q1: Does the text mention Amy buying fruits?</b>
                            <ul>
                                <li>
                                    <b>Yes:</b>
                                    <ul>
                                        <li>
                                            <b>
                                                Q2: Does the text specify the
                                                number of each type of fruit Amy
                                                bought?
                                            </b>
                                            <ul>
                                                <li>
                                                    <b>Yes</b>: 3 apples, 2
                                                    pears, 1 watermelon
                                                    <ul>
                                                        <li>
                                                            <b>Outcome:</b> Amy
                                                            bought a total of 6
                                                            fruits (3 apples + 2
                                                            pears + 1
                                                            watermelon)
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li>
                                                    <b>No:</b>
                                                    <ul>
                                                        <li>
                                                            <b>Outcome:</b> The
                                                            text does not
                                                            provide the specific
                                                            numbers of each
                                                            fruit Amy bought.
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <b>No:</b>
                                    <ul>
                                        <li>
                                            <b>Outcome:</b> The text does not
                                            mention Amy buying any fruit.
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <b>End</b>
                        </li>
                    </ul>
                </p>
            </Alert>
        </div>
    );
};

export default FeedbackSliders;
